// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UploadPayments.Infrastructure.Persistence;

#nullable disable

namespace UploadPayments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UploadPaymentsDbContext))]
    partial class UploadPaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_sha256");

                    b.Property<string>("ContentType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer")
                        .HasColumnName("failed_rows");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_file_name");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<byte[]>("RawCsvBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("raw_csv_bytes");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SucceededRows")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_rows");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<int?>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("payment_uploads", (string)null);
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer")
                        .HasColumnName("failed_rows");

                    b.Property<DateTime?>("HeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at_utc");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<int>("RowEnd")
                        .HasColumnType("integer")
                        .HasColumnName("row_end");

                    b.Property<int>("RowStart")
                        .HasColumnType("integer")
                        .HasColumnName("row_start");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SucceededRows")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_rows");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("payment_upload_chunks", (string)null);
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("HeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at_utc");

                    b.Property<int>("JobType")
                        .HasColumnType("integer")
                        .HasColumnName("job_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at_utc");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.HasIndex("Status", "NextRunAtUtc");

                    b.ToTable("payment_upload_jobs", (string)null);
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<string>("ExtrasJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extras_json");

                    b.Property<string>("MappedFieldsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapped_fields_json");

                    b.Property<string>("RawRowJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_row_json");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_id");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.HasIndex("UploadId", "RowNumber")
                        .IsUnique();

                    b.ToTable("payment_upload_rows", (string)null);
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadRowError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_name");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean")
                        .HasColumnName("is_error");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("message");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<Guid>("UploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_id");

                    b.HasKey("Id");

                    b.HasIndex("UploadId", "RowNumber");

                    b.HasIndex("UploadId", "IsError", "RowNumber");

                    b.ToTable("payment_upload_row_errors", (string)null);
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.ValidationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FieldName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field_name");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("message_template");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parameters_json");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer")
                        .HasColumnName("rule_type");

                    b.Property<int>("Scope")
                        .HasColumnType("integer")
                        .HasColumnName("scope");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("validation_rules", (string)null);
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadChunk", b =>
                {
                    b.HasOne("UploadPayments.Infrastructure.Persistence.Entities.PaymentUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadJob", b =>
                {
                    b.HasOne("UploadPayments.Infrastructure.Persistence.Entities.PaymentUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadRow", b =>
                {
                    b.HasOne("UploadPayments.Infrastructure.Persistence.Entities.PaymentUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UploadPayments.Infrastructure.Persistence.Entities.PaymentUploadRowError", b =>
                {
                    b.HasOne("UploadPayments.Infrastructure.Persistence.Entities.PaymentUpload", null)
                        .WithMany()
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
