# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY UploadPayments.sln ./
COPY src/ ./src/

RUN dotnet restore ./UploadPayments.sln
RUN dotnet publish ./src/UploadPayments.Api/UploadPayments.Api.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

ENV ASPNETCORE_URLS=http://0.0.0.0:8080

COPY --from=build /app/publish ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "UploadPayments.Api.dll"]
