# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY UploadPayments.sln ./
COPY src/ ./src/

RUN dotnet restore ./UploadPayments.sln
RUN dotnet publish ./src/UploadPayments.Worker/UploadPayments.Worker.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish ./

ENTRYPOINT ["dotnet", "UploadPayments.Worker.dll"]
